liip_imagine:
    cache: ~
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        post_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [800, 480], mode: outbound }
                scale:
                    dim: [ 800, 480 ]
        lead_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [ 1440, 480 ], mode: outbound }
                scale:
                    dim: [ 1440, 480 ]
        lead_mobile_thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [ 800, 600 ], mode: outbound }
                scale:
                    dim: [ 800, 600 ]
        avatar:
            quality: 25
            filters:
                thumbnail: { size: [ 500, 500 ], mode: outbound }
        avatar_sm:
            quality: 25
            filters:
                thumbnail: { size: [ 600, 450 ], mode: outbound }